name: Build & Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ===== Checkout code =====
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== Login to Docker Hub =====
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # ===== Build backend Docker image =====
      - name: Build Backend Image
        run: docker build -f Dockerfile.backend -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest .

      # ===== Build frontend Docker image =====
      - name: Build Frontend Image
        run: docker build -f Dockerfile.frontend -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest .

      # ===== Push backend image =====
      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      # ===== Push frontend image =====
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      # ===== Deploy on Test Server via SSH =====
      - name: Deploy on Test Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY}}
          port: 22
          script: |
            echo "=== Installing Docker if not installed ==="
            if ! command -v docker &> /dev/null; then
              sudo apt update -y
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt update -y
              sudo apt install -y docker-ce docker-ce-cli containerd.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            echo "Stopping old containers..."
            sudo  docker rm -f backend || true
            sudo  docker rm -f frontend || true

            echo "Pulling latest images from Docker Hub..."
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

            echo "Running backend container..."
            sudo docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

            echo "Running frontend container..."
            sudo docker run -d --name frontend -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

            echo "Deployment completed successfully!"
