name: Flask Backend CI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        -main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-cors

      # Step 4: Run backend in background
      - name: Start Flask backend
        run: |
          nohup python main.py &
          sleep 5  # give server time to start

      # Step 5: Test API endpoint
      - name: Test API endpoint
        run: |
          curl -f http://127.0.0.1:5000/ || exit 1
          curl -f http://127.0.0.1:5000/data || exit 1

      # Step 6: Cleanup (optional)
      - name: Stop Flask app
        run: pkill -f main.py || true
