name: Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if any)
        run: |
          echo "No tests yet, skipping..."
      
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # Stop old containers if running
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true
  
            # Pull latest images from registry
            docker pull username/backend:latest
            docker pull username/frontend:latest
  
            # Run backend container
            docker run -d --name backend -p 5000:5000 username/backend:latest
  
            # Run frontend container (connects to backend)
            docker run -d --name frontend -p 8080:80 \
              -e BACKEND_URL=http://SERVER_IP:5000 \
              username/frontend:latest
  
